language: node_js
node_js:
  - "8"
env:
  - CXX=g++-4.8
script:
  - yarn build
  - yarn test
deploy:
  provider: script
  script: bash deploy.sh
  skip_cleanup: true
  on:
    branch: master
notifications:
  slack: v2land:xoeT2IXt8yCaUfMxoBbXrSZD
